### ISSUE TITLE
Do not stop watching when javascipt files contain invalid code 

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#11]
Currently gulp fails with an error when the javascript code can not be converted to a valid script file.

I would like to skip building the javascipt files in these cases and wait for further file changes.

**Comment by sebastianhenneberg** [comment]
We can achieve the described behaviour by incorporating [gulp-plumber](https://www.npmjs.com/package/gulp-plumber) into the pipe of the `scripts` task.
