### ISSUE TITLE
Create dedicate test project

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#13]
I would like to create a small test project which makes use of most tasks. On one hand we can use the project to showcase how to use gulp-modular on the other hand it would be good to check that all tasks still work when updating tasks.

**Comment by sebastianhenneberg** [comment]
I had the same in mind. :+1:

**Comment by maxklenk** [comment]
I create a sample app which builds on top of gulp-modular and can be used to test our configurations. https://github.com/maxklenk/angular-sample-app
