### ISSUE TITLE
...would design a nice logo which is ascii art compatible.

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#18]
[Max Klenk](https://www.stomt.com/max-klenk) published this wish on [stomt](https://www.stomt.com/gulp-modular/would-design-a-nice-logo-which-is-ascii-art-compatible).
![attached Image](https://rest.stomt.com/uploads/G8YF/origin/G8YFn6QqDxhQrtftZSBDVZKJQ3RA8FtkBTA0U0xc_origin.png)

**Comment by sebastianhenneberg** [comment]
I have a few things in mind. But it's hard to make them ASCII compatible. We might have to drop that constraint for now unless somebody comes to help us.

**Comment by maxklenk** [comment]
I think if we want we can show "gulp-modular" somewhere when you run the gulp tasks in the command line, a big ascii art image would be too much.

**Comment by sebastianhenneberg** [comment]
:+1:

**Comment by sebastianhenneberg** [comment]
Added first draft of the icon which we will use for the `0.1.0` release. However, it requires some refinement with the paths. We will address this in future releases.
