### ISSUE TITLE
...would compare the task dependencies with the project specific used task to be even more modular.

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#19]
[Max Klenk](https://www.stomt.com/max-klenk) published this wish on [stomt](https://www.stomt.com/gulp-modular/would-compare-the-task-dependencies-with-the-project-specific-used-task-to-be-even-more-modular).
![attached Image]()

**Comment by sebastianhenneberg** [comment]
Duplicate with #16
