### ISSUE TITLE
...would not deploy to gh-pages branch if no branch is specified.

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#23]
[Max Klenk](https://www.stomt.com/max-klenk) published this wish on [stomt](https://www.stomt.com/gulp-modular/would-not-deploy-to-gh-pages-branch-if-no-branch-is-specified).
![attached Image]()

**Comment by sebastianhenneberg** [comment]
What is the expected behaviour? Should we define a meaningful default branch or quit the task with an error message?

**Comment by maxklenk** [comment]
I would prefer to quit the task because the git-deploy may not be intended.
