### ISSUE TITLE
...would add node-sass-globbing

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#36]
My sass files are all over the project, I would like to include them using wildcards which is normally not part of sass, this package helps out:
https://www.npmjs.com/package/node-sass-globbing

**Comment by sebastianhenneberg** [comment]
Awesome, this would allow us to get rid of our `style.scss` file and collect all styles (as we already do with images, JS and HTML).

**Comment by maxklenk** [comment]
We still need a styles.scss file to define the globs and other imports (the order for configs is important)

**Comment by sebastianhenneberg** [comment]
Isn't there a package to determine the right order?

**Comment by maxklenk** [comment]
i don't know, but there wont be one the knows automatically which are the base styles (for forms..) and what should overwrite them.
