### ISSUE TITLE
Rebuild vendor files when bower-file changes

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#4]
A watcher on the bower-file could automatically include newly added libraries.

**Comment by sebastianhenneberg** [comment]
The package [gulp-watch](https://www.npmjs.com/package/gulp-watch) (do not confuse with `gulp.watch`) provides the capability to watch on the file system for new or removed files.

**Comment by sebastianhenneberg** [comment]
I had to introduce a little workaround into the `vendor*` tasks because `newer()` prevented further processing. Please have look at it.
