### ISSUE TITLE
Add optional debug flag

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#5]
I use [gulp-debug](https://www.npmjs.com/package/gulp-debug) review which data is passed throw the pipes. This is most important when reviewing which files are include when using main-bower-files.

**Comment by sebastianhenneberg** [comment]
Do you debug all tasks simultaneously? I prefer an optional debug flag for each pipeline because I'm usually interested in a particular pipeline. Otherwise, the output can become pretty verbose on bigger projects.

**Comment by maxklenk** [comment]
It would work with a global `--debug` flag, if you only execute 'gulp venderScripts `--debug` you are able to review this task, executing `gulp --debug` would for sure show all debug messages we define.
