### ISSUE TITLE
Only depend on necessary dependencies

### ISSUE THREAD

**Issue by chinesedfan** [ONE-LOGIC/gulp-modular#52]
I like the idea that providing a lot of predefined tasks and configure them.

But with tasks increase, `gulp-modular` will depend on more and more packages. If I just need 1 or 2 tasks, how to exclude those unnecessary dependencies?

**Comment by maxklenk** [comment]
Hi, many tasks are interconnected with other tasks or dependencies. This makes it difficult to specify a own dependency set for each task. We want to keep it as simple as possible for the user to get started with gulp-modular without thinking about the dependencies he needs.

We are working on isolating different parts and moving them in own modules. This makes it easy to only add them when they are used. We already extracted: https://github.com/ONE-LOGIC/gulp-modular-karma and https://github.com/ONE-LOGIC/gulp-modular-release and planning to make the deploy tasks optional. Do you think there are other tasks that should not be included in the default task set?

**Comment by chinesedfan** [comment]
No. I just wonder how to keep dependencies of `gulp-modular` as less as possible. Thanks for your reply!
