### ISSUE TITLE
...would expose the css autoprefixer options in the config.

### ISSUE THREAD

**Issue by maxklenk** [ONE-LOGIC/gulp-modular#56]
The autoprefixer options are set to:

``` javascript
var optionsPrefixer = {
      browsers: ['last 2 versions'],
      cascade: false
};
```

Depending on the application the [browser support](http://browserl.ist/?q=last+2+versions) may not be enough, so we should be able to configure that in the config.

**Comment by niklaszantner** [comment]
Yeah, we also just stumbled across that one. Should definitely be exposed and at least be lifted to something like `browsers: ['>0.5%']`.
